

spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: false # Disabled config server
    discovery:
      enabled: true # Enabled eureka discovery server
    gateway:
      discovery:
        locator:
          lower-case-service-id: true  # Enable gateway to read also ms with lower-case instead of upper-case

server:
  port: 8888

