
server:
  port: 8761  # Default port for Eureka Server

spring:
  application:
    name: eureka-service
  profiles:
    active: docker
eureka:
  instance:
    hostname: eureka-service
  client:
    register-with-eureka: false  # Eureka server does not need to register itself
    fetch-registry: false        # Do not fetch registry on Eureka server
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL=http:http://eureka-service:8761/eureka}  # URL for the Eureka server
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    eureka:
      enabled: true
