
server:
  port: 8761  # Default port for Eureka Server

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: eureka-server


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # Eureka server does not need to register itself
    fetch-registry: false        # Do not fetch registry on Eureka server
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # URL for the Eureka server
  server:
    enable-self-preservation: false

